// <auto-generated />
namespace major_data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201607070 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201607070));
        
        string IMigrationMetadata.Id
        {
            get { return "201607071728008_20160707-0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
