// <auto-generated />
namespace web_client_usdep.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201606290 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201606290));
        
        string IMigrationMetadata.Id
        {
            get { return "201606291040468_20160629-0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
